apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: skyrim-together
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: gaming
  project: default
  source:
    path: charts/skyrim-together/
    repoURL: https://github.com/heywoodlh/nixos-k8s-cluster
    targetRevision: {{ .Values.version }}
    directory:
      recurse: false
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
