argo-cd:
  installCRDs: false
  global:
    image:
      tag: v2.6.4
      repository: docker.io/argoproj/argocd
  dex:
    enabled: true
  server:
    extraArgs:
      - --insecure
    config:
      repositories: |
        - type: helm
          name: stable
          url: https://charts.helm.sh/stable
        - type: helm
          name: argo-cd
          url: https://argoproj.github.io/argo-helm
      kustomize.buildOptions: "--enable-helm"
    ingress:
      enabled: true 
      paths:
        - /argo
      pathType: Prefix
      ingressClassName: nginx
