apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system 
helmCharts:
- name: nfs-subdir-external-provisioner
  repo: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner
  version: 4.0.17
  releaseName: nfs-client
  namespace: default
  valuesFile: values.yaml
